
user                                nginx    nginx;

worker_processes                    auto;
worker_cpu_affinity                 auto;
worker_rlimit_nofile                65535;

error_log                           /var/log/nginx/error.log    warn;

pid                                 /var/run/nginx.pid;

events {
    worker_connections              auto;
    use                             epoll;
    multi_accept                    on;
    accept_mutex                    off;
}

stream {
    include                        stream.conf.d/*.conf;
    include                        stream.conf.d/*/*.conf;
    include                        stream.conf.d/*/*/*.conf;
}

http {
    include                         conf/mime.types;

    proxy_connect_timeout           30;
    proxy_send_timeout              60;
    proxy_read_timeout              60;

    proxy_buffering                 on;
    proxy_buffer_size               4k;
    proxy_buffers                   4    32k;
    proxy_busy_buffers_size         64k;
    proxy_temp_file_write_size      64k;

    proxy_next_upstream             error    timeout    invalid_header    http_502    http_504;

    include                         conf/snippets/real_ip.conf;
    include                         conf/snippets/optimize.conf;
    include                         conf/snippets/security.conf;
    include                         conf/snippets/log_format.conf;

    default_type                    application/octet-stream;
    charset                         utf-8;

    sendfile                        on;
    tcp_nopush                      on;
    tcp_nodelay                     on;

    include                         http.conf.d/*.conf;
    include                         http.conf.d/*/*.conf;
    include                         http.conf.d/*/*/*.conf;
}
